# -*- coding: utf-8 -*-
# ---------------------------------------------------------------------------
# errorScript.py
# Created on: 2018-12-07 11:07:18.00000
#   (generated by ArcGIS/ModelBuilder)
# Usage: errorScript <Output_Folder> <Select_Main_Lines> <Select_Service_Lines> <Select_wMeter> <Select_wControlValve> <Select_wHydrant> <Select_wFitting> <Select_wPump> <Select_wFireHydrant>
# Description:
# This tool checks connectivity between point features and line features in a Water System Feature Dataset
# ---------------------------------------------------------------------------

# Import arcpy module
import arcpy

arcpy.env.workspace =

# Script arguments
Output_Folder = arcpy.GetParameterAsText(0)

Select_Main_Lines = arcpy.GetParameterAsText(1)

Select_Service_Lines = arcpy.GetParameterAsText(2)

Select_wMeter = arcpy.GetParameterAsText(3)

Select_wControlValve = arcpy.GetParameterAsText(4)

Select_wHydrant = arcpy.GetParameterAsText(5)

Select_wFitting = arcpy.GetParameterAsText(6)

Select_wPump = arcpy.GetParameterAsText(7)

Select_wFireHydrant = arcpy.GetParameterAsText(8)

# Local variables:
Output_Selection = Select_wMeter
Output_Selection__2_ = Select_Main_Lines
Output_Selection__3_ = Select_Main_Lines
Output_Selection__4_ = Select_Main_Lines
Output_Selection__5_ = Select_Main_Lines
Output_Selection__6_ = Select_Main_Lines
Points_on_line_Selection = Output_Selection
Points_on_line_Selection__2_ = Select_Service_Lines
Points_on_line_Selection__3_ = Select_Service_Lines
Points_on_line_Selection__4_ = Select_Service_Lines
Points_on_line_Selection__5_ = Select_Service_Lines
Points_on_line_Selection__6_ = Select_Service_Lines
Meters_not_touching_line = Points_on_line_Selection
Pump_not_touching_line = Points_on_line_Selection__2_
Hydrants_not_touching_line = Points_on_line_Selection__3_
Fitting_not_touching_line = Points_on_line_Selection__4_
Water_Valves_not_touching_line = Points_on_line_Selection__6_
Fire_Hydrants_not_touching_line = Points_on_line_Selection__5_
Output_Layer_Name = Fire_Hydrants_not_touching_line
Derived_Folder = Output_Folder

# Process: Select Layer By Location
arcpy.SelectLayerByLocation_management(Select_wMeter, "HAVE_THEIR_CENTER_IN", Select_Main_Lines, "", "NEW_SELECTION", "NOT_INVERT")

# Process: Select Layer By Location (2)
arcpy.SelectLayerByLocation_management(Output_Selection, "HAVE_THEIR_CENTER_IN", Select_Service_Lines, "", "ADD_TO_SELECTION", "NOT_INVERT")

# Process: Select Layer By Location (3)
arcpy.SelectLayerByLocation_management(Points_on_line_Selection, "INTERSECT", "", "", "SWITCH_SELECTION", "NOT_INVERT")

# Process: Select Layer By Location (4)
arcpy.SelectLayerByLocation_management(Select_wPump, "HAVE_THEIR_CENTER_IN", Select_Main_Lines, "", "NEW_SELECTION", "NOT_INVERT")

# Process: Select Layer By Location (9)
arcpy.SelectLayerByLocation_management(Output_Selection__2_, "HAVE_THEIR_CENTER_IN", Select_Service_Lines, "", "ADD_TO_SELECTION", "NOT_INVERT")

# Process: Select Layer By Location (12)
arcpy.SelectLayerByLocation_management(Points_on_line_Selection__2_, "INTERSECT", "", "", "SWITCH_SELECTION", "NOT_INVERT")

# Process: Select Layer By Location (5)
arcpy.SelectLayerByLocation_management(Select_wHydrant, "HAVE_THEIR_CENTER_IN", Select_Main_Lines, "", "NEW_SELECTION", "NOT_INVERT")

# Process: Select Layer By Location (10)
arcpy.SelectLayerByLocation_management(Output_Selection__3_, "HAVE_THEIR_CENTER_IN", Select_Service_Lines, "", "ADD_TO_SELECTION", "NOT_INVERT")

# Process: Select Layer By Location (13)
arcpy.SelectLayerByLocation_management(Points_on_line_Selection__3_, "INTERSECT", "", "", "SWITCH_SELECTION", "NOT_INVERT")

# Process: Select Layer By Location (6)
arcpy.SelectLayerByLocation_management(Select_wFitting, "HAVE_THEIR_CENTER_IN", Select_Main_Lines, "", "NEW_SELECTION", "NOT_INVERT")

# Process: Select Layer By Location (11)
arcpy.SelectLayerByLocation_management(Output_Selection__4_, "HAVE_THEIR_CENTER_IN", Select_Service_Lines, "", "ADD_TO_SELECTION", "NOT_INVERT")

# Process: Select Layer By Location (14)
arcpy.SelectLayerByLocation_management(Points_on_line_Selection__4_, "INTERSECT", "", "", "SWITCH_SELECTION", "NOT_INVERT")

# Process: Select Layer By Location (16)
arcpy.SelectLayerByLocation_management(Select_wControlValve, "HAVE_THEIR_CENTER_IN", Select_Main_Lines, "", "NEW_SELECTION", "NOT_INVERT")

# Process: Select Layer By Location (17)
arcpy.SelectLayerByLocation_management(Output_Selection__6_, "HAVE_THEIR_CENTER_IN", Select_Service_Lines, "", "ADD_TO_SELECTION", "NOT_INVERT")

# Process: Select Layer By Location (18)
arcpy.SelectLayerByLocation_management(Points_on_line_Selection__6_, "INTERSECT", "", "", "SWITCH_SELECTION", "NOT_INVERT")

# Process: Select Layer By Location (7)
arcpy.SelectLayerByLocation_management(Select_wFireHydrant, "HAVE_THEIR_CENTER_IN", Select_Main_Lines, "", "NEW_SELECTION", "NOT_INVERT")

# Process: Select Layer By Location (8)
arcpy.SelectLayerByLocation_management(Output_Selection__5_, "HAVE_THEIR_CENTER_IN", Select_Service_Lines, "", "ADD_TO_SELECTION", "NOT_INVERT")

# Process: Select Layer By Location (15)
arcpy.SelectLayerByLocation_management(Points_on_line_Selection__5_, "INTERSECT", "", "", "SWITCH_SELECTION", "NOT_INVERT")

# Process: Select Layer By Attribute
arcpy.SelectLayerByAttribute_management(Fire_Hydrants_not_touching_line, "REMOVE_FROM_SELECTION", "CONNECTIONPOINT = 'buildingDryStandpipe'")

# Process: Feature Class To Shapefile (multiple)
arcpy.FeatureClassToShapefile_conversion("'';'';'';'';'';''", Output_Folder)

